#Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2,
# the first 10 terms will be:
#1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
#By considering the terms in the Fibonacci sequence whose values do not exceed four million,
# find the sum of the even-valued terms.
c=0
a=1
b=2
series=[a,b]
while c<4000000:
    c=a+b
    a=b
    b=c
    if b<4000000:
        series.append(b)
sum=0
for i in range(len(series)):
    if series[i]%2==0:
        sum+=series[i]
print("The sum of the even-valued terms in the Fibonacci sequence with terms whose values do not exceed four million "
      "is " + str(sum))